name: Update foo
on:
  repository_dispatch:
    types: release

jobs:
  updateFoo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update foo file
        run: |
          curl https://raw.githubusercontent.com/das-l/workflow-test-src/master/foo > foo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update foo"
          git push
