name: Update foo
on:
  repository_dispatch:
    types: release

jobs:
  updateFoo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update foo file
        run: |
          git clone https://github.com/das-l/workflow-test-src.git
          cp -a workflow-test-src/foo foo
          rm -rf workflow-test-src
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet && git diff --staged --quiet || git commit -am "Update ${{ github.event.client_payload.ref }}"
          git push
