name: Update foo
on:
  repository_dispatch:
    types: release

jobs:
  updateFoo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update foo file
        run: |
          echo `date +%s` > foo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update foo
          title: Update foo
          body: Add current timestamp to foo file
          branch: update-foo
